FIX: Imports were failing
BUG: ImportError: cannot import name 'Visualizer'
The command "python manage.py makemigrations" failed and exited with 1 during.
FIX: Deleting unused imports